name: llm
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pip
  - python=3.11
  - pip:
    - black
    - flake8
    - isort
    - jupyter
    - openpyxl
    - hydra-core
    - matplotlib
    - seaborn
    - numpy
    - pandas
    - plotly
    - polars
    - prettytable
    - pyarrow
    - scikit-learn
    - scipy
    - tqdm
